### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by akbstone** [akbstone/erddap-parser-js#1]

**Comment by 7yl4r** [comment]
I just pushed 0.0.5 into npm using the basic instructions [here](https://zellwk.com/blog/publish-to-npm/).

I will now be testing out installing from npm:

https://github.com/USF-IMARS/grafana-erddap/blob/d6dcd0ab31022451c9c8d9bbc18d930ce3365aad/package.json#L47

**Comment by 7yl4r** [comment]
comment here w/ your npm username if you want to be added as a maintainer of the npm package and I'll add you.
